services:
  pulsar:
    build:
      context: ./conf/pulsar                # Thư mục chứa Dockerfile, script, schema
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8081:8080"    # Thay đổi port host thành 8081
    restart: unless-stopped
    command: ["/pulsar/init-pulsar.sh"]


  fluent-bit:
    build:
      context: ./conf/fluent-bit         # Thư mục chứa Dockerfile, fluent-bit.conf, parsers.conf
      dockerfile: Dockerfile   # Có thể bỏ qua nếu file tên mặc định
    container_name: fluent-bit
    restart: unless-stopped
    volumes:
      - /d/DockerData/realtime-log-pipeline/data:/var/log/nginx:rw
    ports:
      - "2020:2020"
    depends_on:
      - pulsar-bridge
    environment:
      - TZ=Asia/Ho_Chi_Minh

  pulsar-bridge:
    build:
      context: ./conf/pulsar-bridge
    container_name: pulsar-bridge
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - pulsar
    environment:
      - TZ=Asia/Ho_Chi_Minh
